### ISSUE TITLE
Make Top Button Bar

### ISSUE THREAD

**Issue by aarora4** [aarora4/VotingChromeExtension#1]
This task is responsible for creating the three buttons that are at the top of the chrome extension.

These buttons include the on/off switch, the flag button, and the exit button.

**Tasks:**
- [x] Make an on/off button. For now, this button should just be able to switch on and off, and look similar to the mockup. **The button doesn't need to be functional yet.**
- [x] Make a button that has the flag icon. **It should be clickable but it doesn't have to do anything yet.**
- [ ] Make the exit button as it looks in the mockup. It should be a cross and a circle. **This also doesn't need to be hooked up yet**
- [x] Make sure all buttons are the same height and are positioned relative to eachother like they are in the mockup
<img width="377" alt="Screen Shot 2021-02-12 at 12 03 21 AM" src="https://user-images.githubusercontent.com/25010271/107732427-50366a80-6cc6-11eb-8b11-cd69811b938b.png">

**Comment by aarora4** [comment]
Check here for information on how to get started adding UI elements to our extension: https://developer.chrome.com/docs/extensions/mv2/user_interface/

**Comment by aarora4** [comment]
Test your UI code here: https://jsfiddle.net/
It'll be easier to just try different things here without loading the whole extension each time
