### ISSUE TITLE
Page One of Statement Detail Card

### ISSUE THREAD

**Issue by aarora4** [aarora4/VotingChromeExtension#5]
- [x] Circle in the middle with a border of color #707070
- [x] Title label
- [x] Rating (true/false) label
- [x] Learn more label, underlined
- [x] Outline the whole card with a rounded border of color #707070
- [ ] Use proper fonts and colors. Official red, green and gray colors are, #FF907C, #8BE5B3, and #707070 respectively

Ignore the two dots at the bottom for now. You can download the fonts on googlefonts. Use JSFiddle again for rapid iteration. 

![Screen Shot 2021-02-28 at 2 10 56 AM](https://user-images.githubusercontent.com/25010271/109410810-a4e71000-796b-11eb-833b-9137446c2b6b.png)
<img width="264" alt="Screen Shot 2021-02-28 at 2 10 56 AM" src="https://user-images.githubusercontent.com/25010271/109410817-a9132d80-796b-11eb-865a-91619e743620.png">
